name: DEV (k8s)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Deploy to k8s
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            ./autodeploy_scs.sh dummy >> ~/deploy.log 2>&1
            sleep 2m
            ./autodeploy_scs.sh stable >> ~/deploy.log 2>&1
